### ISSUE TITLE
Pico Zero compatibility

### ISSUE THREAD

**Issue by Roet-Ivar** [DavidPagels/retro-pico-switch#29]
Hi. I've flashed the USB-version of you project onto a pico Zero using the tiny solder point for GP18, although nothing shows up on my pc after flashing  the board so I wonder if it's possible to make this compatible with a pico zero?

Thanks!

**Comment by DavidPagels** [comment]
This project was coded specifically for the architecture of the RP2040 and won't work with a raspberry pi zero without a significant rewrite.

**Comment by Roet-Ivar** [comment]
Hi. I think you might've miss read my question. I'm actually using a RP2040 Pico Zero (a tiny version of the rpi pico), but whenever I flash the usb-firmware it bricks the device. Thank you!

**Comment by DavidPagels** [comment]
Ah, yep, I read too quickly. Did you also solder a pull up resistor to pin 18?

**Comment by Roet-Ivar** [comment]
> Ah, yep, I read too quickly. Did you also solder a pull up resistor to pin 18?

I did add a 1K resistor between data and 3.3v. Does this prevent it from being properly flashed you think? I always have to revert the firmware to unbrick it. Many thanks!

**Comment by DavidPagels** [comment]
I wouldn't think so. It should just work. The pico zero is just an rp2040 on a different board.

**Comment by Roet-Ivar** [comment]
> I wouldn't think so. It should just work. The pico zero is just an rp2040 on a different board.

I thought so too. I tried two pico zero boards just in case, this fw does not like them for some reason :)

**Comment by Roet-Ivar** [comment]
Wait. Your very first firmware "n64_pico_switch.uf2" actually showed up as a "POKKEN CONTROLLER", all the other firmwares doesn't. Hmm so the board can be flashed at least. I wonder if the zero's 2MB flash could be a problem? I think the original full size board has 16MB.

@DavidPagels let me know if you want to me to test anything, I'm ofc not expecting you to put time into to this, I do think your project is perfect for making small footprint gc adapters (even have some 3d print model in the works for the smaller one).

**Comment by Arakon** [comment]
I can confirm that it works on a Zero just fine.
Using GP18, 1K resistor.
Make sure you got your wiring right and that the grounds are both connected.

**Comment by DavidPagels** [comment]
Resolved in #31

**Comment by Roet-Ivar** [comment]
> I can confirm that it works on a Zero just fine. Using GP18, 1K resistor. Make sure you got your wiring right and that the grounds are both connected.

My issue is that the device no longer shows up in device manager after flashing, what fw version are you using?
I'm thinking it should still show up as a controller even if I haven't connected anything but the zero.
